# Numpy practise questions

1. Create a NumPy array of shape(3,3) with values ranging    from 1 to 9.

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Manually adding elements
print(arr)
print("Array shape:", arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)


In [2]:
arr2 = np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10)]) #using arange to add elements
print(arr2)
print("Array shape:", arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)


2. Given a 1D array [10,20,30,40,50], write code to reverse the array 

In [3]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
npa = np.array(arr3[::-1]) #Reversing the array
#how does this work? The slicing operation arr3[::-1] creates a reversed view of arr3, and then np.array() constructs a new NumPy array from that reversed view.
print(npa)

[9 8 7 6 5 4 3 2 1]


3. create a 5x5 array filled with zeros and set the value of the middle element to 1

In [4]:
arr4 =  np.array(np.zeros((5,5)))
print(arr4)
print ('\n')
arr4[2,2] =1 
print(arr4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


4. Genrate a numpy array with 20 random integers between 1 to 100. Replace all the even numbers with -1.

In [7]:
arr5 = np.random.randint(1,100,20) #Random array of 20 elements between 1 and 100
print(arr5)
print(np.where(arr5%2==0, -1, arr5)) #Replace even numbers with -1

[89 71 34 62 28 27 91 15 44 12  4 81 61 55 31 16 52 81  9 51]
[89 71 -1 -1 -1 27 91 15 -1 -1 -1 81 61 55 31 -1 -1 81  9 51]


5. given a numpy array a =np.array([[1,2],[3,4],[5,6]]), extract the second column.

In [11]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print('\n')
print(a[:,1])  # Accessing second column

[[1 2]
 [3 4]
 [5 6]]


[2 4 6]


6.Create a numpy array with values [1,2,3,4] and convert it into 2x2 matrix.

In [12]:
b = np.array([1,2,3,4])
b.reshape(2,2)  #Reshaping 1D array to 2D array

array([[1, 2],
       [3, 4]])

7. create two numpy arrays of shape (2,2) and perform element wise addition , subctractuon, multiplication, and division.

In [15]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print(c+d)  #Element wise addition of two arrays
print('\n')
print(c*d)  #Element wise multiplication of two arrays
print('\n')
print(c-d)  #Element wise subtraction of two arrays
print('\n')
print(c/d)  #Element wise division of two arrays

[[ 6  8]
 [10 12]]


[[ 5 12]
 [21 32]]


[[-4 -4]
 [-4 -4]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


8.Use numpy to create an array of linearly spaced values between 0 and 1.

In [18]:
mah = np.linspace(0,1,5)  #Array with 5 values between 0 and 10
print(mah)

[0.   0.25 0.5  0.75 1.  ]


9. create a numpy array and demostrate how to compute its mean, median and standard deviation.

In [22]:
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(e))  #Mean of all elements
print(np.median(e))  #Median of all elements
print(np.std(e))  #Standard deviation of all elements

5.0
5.0
2.581988897471611


10.Given a 2D numpy array,, write a function to normalize each column(substract mean and dicvide by std deivation)

In [23]:
norm = np.array([[1,2,3],[4,5,6],[7,8,9]])

def normalize_array(n):
    mean = n.mean(axis=0)
    std = n.std(axis =0)
    normalized = (n-mean)/std
    return normalized

print(normalize_array(norm))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
