 # Numpy in python

numpy is a genral purpose array processing package. it provides a high performance multidimensional array object, and tools for working with these arrays.

Numpy- 1. Stores nummbers contiguously in memory 2.uses complied c code 3.performs vectorized operations(doing the same math on many numbers at once, without writing loops)

numpy.ndarray - an n-dimensional array is 1. a fixed size grid if numbers 2. all the same datatypes 3.stored efficiently in memory 



In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print("Original array:", arr)


Original array: [1 2 3 4 5]


In [4]:
type(arr) #this prints the type of the array

numpy.ndarray

In [5]:
print(arr[2]) # accessing the 3rd element of the array
arr[2] = 10  # modifying the 3rd element of the array
print("Modified array:", arr)

3
Modified array: [ 1  2 10  4  5]


In [6]:
arr1 = np.array([1,'Mahek',94,'Pune'])
print("Array with multiple data types:", arr1)
print("Data type of arr1:", arr1.dtype)

Array with multiple data types: ['1' 'Mahek' '94' 'Pune']
Data type of arr1: <U21


In [ ]:
arr * 2  # This will multiply each element in the array by 2

array([ 2,  4, 20,  8, 10])

In [8]:
a = np.arange(11) # creates an array with values from 0 to 10
print("Array using arange:", a)

Array using arange: [ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
np.arange(529,550,2) # creates an array from 529 to 549 with a step of 2    

array([529, 531, 533, 535, 537, 539, 541, 543, 545, 547, 549])

In [10]:
np.arange(-30,20,8) # creates an array from -30 to 19 with a step of 8

array([-30, -22, -14,  -6,   2,  10,  18])

In [11]:
arr

array([ 1,  2, 10,  4,  5])

In [12]:
arr.ndim # prints the number of dimensions of the array

1

In [13]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("2D Array:\n", arr3)
arr3.ndim  # prints the number of dimensions of arr3

2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


2

In [14]:
arr3.shape  # returns the shape of the array

(5, 3)

In [15]:
arr3.flatten() # flattens the 2D array to 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr3.flatten().ndim  # prints the number of dimensions of the flattened array

1

In [17]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
arr3.reshape(3,5)  # reshapes the array to 3x5 matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
arr3.reshape(15,1)  # reshapes the array to 15x1 matrix

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [20]:
arr4 = np.arange(3,13) # creates an array from 3 to 12
arr4

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr4[3:7]  # Slicing the array from index 3 to 6

array([6, 7, 8, 9])

In [22]:
np.mean(arr4)  # calculates the mean of the array elements

np.float64(7.5)

In [23]:
np.std(arr4)  # calculates the standard deviation of the array elements

np.float64(2.8722813232690143)

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])  
a + b  # element-wise addition of two arrays

array([ 7,  9, 11, 13, 15])

In [25]:
a @ b  # dot product of two arrays

np.int64(130)

In [26]:
np.dot(a,b)  # another way to compute the dot product of two arrays

np.int64(130)

In [27]:
np.linalg.det(np.array([[1,2],[3,4]]))  # calculates the determinant of a 2x2 matrix

np.float64(-2.0000000000000004)

In [28]:
a= np.array([[1,2],[3,4]])
np.linalg.inv(a)  # computes the inverse of a square matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
np.linalg.eig(a) # computes the eigenvalues and right eigenvectors of a square matrix, eig 

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [30]:
vec = np.array([3,6])
np.linalg.norm(vec)

np.float64(6.708203932499369)

In [31]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {int, float, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes`` for what values are
        supported for matrices and vectors respectively). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple